import MenuItem from '../components/MenuItem/MenuItem';
import { menuTags } from '../data/menu';
import recipes from '../data/recipes/recipes';
import Head from 'next/head';

const Menu = ({ recipes }) => {
    console.log('recipes', recipes);
    console.log('test');
    return (
        <div>
            <Head>
                <title>The House Menu</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
                <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Poppins&display=swap" rel="stylesheet"></link>
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <h1>The House Menu</h1>
            <MenuItem />
            {menuTags.map((tag) => (<h4 key={tag}>{tag}</h4>))}
        </div>
    )
}

export async function getStaticProps(context) {
    return {
        props: { recipes }
    }
}

export default Menu;
