import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Watchlist.module.css'
import data from '../data/october.json';

const Watchlist = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Now Playing on Blockbuster</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          The Watchlist
        </h1>

        <div className={styles.content}>
          {
            data.map((category, i) => {
              const { categoryName, items } = category;
                return (
                  <div className={styles.category} key={`cat-${i}`}>
                    <h2>{ categoryName }</h2>
                    { items.map((item, i) => <Tile {...item} key={`item-${i}`} />) }
                  </div>
                )
            })
          }
        </div>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}

const Tile = (props) => {
  const { title, youtube, year } = props;
  return (
    <div className={styles.tile}>
      <h3>{ title } ({ year })</h3>
      <p>{ youtube }</p>
    </div>
  )
}

export default Watchlist;
